### ISSUE TITLE
关闭连接报错

### ISSUE THREAD

**Issue by yirenyishi** [mootdx/mootdx#29]
```
class TdxClient():

    def __init__(self):
        dlog("初始化tdx链接")
        self.client = Quotes.factory(market='std', multithread=True, heartbeat=True, bestip=False,
                                     verbose=0, quiet=False, timeout=15)

    def getClient(self):
        if self.client.closed:
            `dlog("tdx链接断开，重新连接")`
            self.client = Quotes.factory(market='std', multithread=True, heartbeat=True, bestip=False,
                                         verbose=0, quiet=False, timeout=15)
        return self.client

    def close(self):
        if not self.client.closed:
            dlog("tdx链接自动断开")
            self.client.close()
```

close的时候报错，错误代码如下
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/tdxpy/base_socket_client.py", line 223, in disconnect
    self.client.shutdown(socket.SHUT_RDWR)
OSError: [Errno 107] Transport endpoint is not connected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/code/task/stock_his_task.py", line 115, in updateStockInfo
    spider.tdxClient.close()
  File "/code/spider/tdx_client.py", line 22, in close
    self.client.close()
  File "/usr/local/lib/python3.10/site-packages/mootdx/quotes.py", line 89, in close
    hasattr(self.client, "close") and self.client.close()
  File "/usr/local/lib/python3.10/site-packages/tdxpy/base_socket_client.py", line 240, in close
    self.disconnect()
  File "/usr/local/lib/python3.10/site-packages/tdxpy/base_socket_client.py", line 229, in disconnect
    raise TdxConnectionError(f"disconnect err: {e}")
tdxpy.exceptions.TdxConnectionError: disconnect err: [Errno 107] Transport endpoint is not connected
```

**Comment by bopo** [comment]
新版本已经修复
