### ISSUE TITLE
 600664取月线报错

### ISSUE THREAD

**Issue by allon2** [mootdx/mootdx#31]
month must be in 1..12: 0-00-00 15:00 present at position 102
Traceback (most recent call last):
  File "D:\anaconda3\envs\chanlunpy38\lib\site-packages\dateutil\parser\_parser.py", line 649, in parse
    ret = self._build_naive(res, default)
  File "D:\anaconda3\envs\chanlunpy38\lib\site-packages\dateutil\parser\_parser.py", line 1235, in _build_naive
    naive = default.replace(**repl)
ValueError: month must be in 1..12

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pandas\_libs\tslib.pyx", line 605, in pandas._libs.tslib.array_to_datetime
  File "pandas\_libs\tslibs\parsing.pyx", line 320, in pandas._libs.tslibs.parsing.parse_datetime_string
  File "D:\anaconda3\envs\chanlunpy38\lib\site-packages\dateutil\parser\_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "D:\anaconda3\envs\chanlunpy38\lib\site-packages\dateutil\parser\_parser.py", line 651, in parse
    six.raise_from(ParserError(str(e) + ": %s", timestr), e)
  File "<string>", line 3, in raise_from
dateutil.parser._parser.ParserError: month must be in 1..12: 0-00-00 15:00

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pandas\_libs\tslib.pyx", line 616, in pandas._libs.tslib.array_to_datetime
TypeError: invalid string coercion to datetime for "0-00-00 15:00" at position 102

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda3\envs\chanlunpy38\lib\site-packages\dateutil\parser\_parser.py", line 649, in parse
    ret = self._build_naive(res, default)
  File "D:\anaconda3\envs\chanlunpy38\lib\site-packages\dateutil\parser\_parser.py", line 1235, in _build_naive
    naive = default.replace(**repl)
ValueError: month must be in 1..12

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\OpenSource\books\czsc_all\yijixiuxin\chanlun\cl_v2\exchange_tdx.py", line 202, in batch_bars
    data=getTdXCLientInstance().bars(symbol=symbol, frequency=frequency, start=istart, offset=offset)
  File "D:\anaconda3\envs\chanlunpy38\lib\site-packages\mootdx\quotes.py", line 213, in bars
    return to_data(result, symbol=symbol, client=self, **kwargs)
  File "D:\anaconda3\envs\chanlunpy38\lib\site-packages\mootdx\utils\__init__.py", line 165, in to_data
    result.index = pd.to_datetime(result.datetime)
  File "D:\anaconda3\envs\chanlunpy38\lib\site-packages\pandas\core\tools\datetimes.py", line 1068, in to_datetime
    values = convert_listlike(arg._values, format)
  File "D:\anaconda3\envs\chanlunpy38\lib\site-packages\pandas\core\tools\datetimes.py", line 438, in _convert_listlike_datetimes
    result, tz_parsed = objects_to_datetime64ns(
  File "D:\anaconda3\envs\chanlunpy38\lib\site-packages\pandas\core\arrays\datetimes.py", line 2177, in objects_to_datetime64ns
    result, tz_parsed = tslib.array_to_datetime(
  File "pandas\_libs\tslib.pyx", line 427, in pandas._libs.tslib.array_to_datetime
  File "pandas\_libs\tslib.pyx", line 683, in pandas._libs.tslib.array_to_datetime
  File "pandas\_libs\tslib.pyx", line 829, in pandas._libs.tslib._array_to_datetime_object
  File "pandas\_libs\tslib.pyx", line 819, in pandas._libs.tslib._array_to_datetime_object
  File "pandas\_libs\tslibs\parsing.pyx", line 320, in pandas._libs.tslibs.parsing.parse_datetime_string
  File "D:\anaconda3\envs\chanlunpy38\lib\site-packages\dateutil\parser\_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "D:\anaconda3\envs\chanlunpy38\lib\site-packages\dateutil\parser\_parser.py", line 651, in parse
    six.raise_from(ParserError(str(e) + ": %s", timestr), e)
  File "<string>", line 3, in raise_from
dateutil.parser._parser.ParserError: month must be in 1..12: 0-00-00 15:00 present at position 102

month must be in 1..12: 0-00-00 15:00 present at position 102
Traceback (most recent call last):
  File "D:\anaconda3\envs\chanlunpy38\lib\site-packages\dateutil\parser\_parser.py", line 649, in parse
    ret = self._build_naive(res, default)
  File "D:\anaconda3\envs\chanlunpy38\lib\site-packages\dateutil\parser\_parser.py", line 1235, in _build_naive
    naive = default.replace(**repl)
ValueError: month must be in 1..12

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pandas\_libs\tslib.pyx", line 605, in pandas._libs.tslib.array_to_datetime
  File "pandas\_libs\tslibs\parsing.pyx", line 320, in pandas._libs.tslibs.parsing.parse_datetime_string
  File "D:\anaconda3\envs\chanlunpy38\lib\site-packages\dateutil\parser\_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "D:\anaconda3\envs\chanlunpy38\lib\site-packages\dateutil\parser\_parser.py", line 651, in parse
    six.raise_from(ParserError(str(e) + ": %s", timestr), e)
  File "<string>", line 3, in raise_from
dateutil.parser._parser.ParserError: month must be in 1..12: 0-00-00 15:00

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pandas\_libs\tslib.pyx", line 616, in pandas._libs.tslib.array_to_datetime
TypeError: invalid string coercion to datetime for "0-00-00 15:00" at position 102

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda3\envs\chanlunpy38\lib\site-packages\dateutil\parser\_parser.py", line 649, in parse
    ret = self._build_naive(res, default)
  File "D:\anaconda3\envs\chanlunpy38\lib\site-packages\dateutil\parser\_parser.py", line 1235, in _build_naive
    naive = default.replace(**repl)
ValueError: month must be in 1..12

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "..\exchange_tdx.py", line 284, in bars_history
    data=getTdXCLientInstance().bars(symbol=symbol, frequency=freq, start=0, offset=offset)
  File "D:\anaconda3\envs\chanlunpy38\lib\site-packages\mootdx\quotes.py", line 213, in bars
    return to_data(result, symbol=symbol, client=self, **kwargs)
  File "D:\anaconda3\envs\chanlunpy38\lib\site-packages\mootdx\utils\__init__.py", line 165, in to_data
    result.index = pd.to_datetime(result.datetime)
  File "D:\anaconda3\envs\chanlunpy38\lib\site-packages\pandas\core\tools\datetimes.py", line 1068, in to_datetime
    values = convert_listlike(arg._values, format)
  File "D:\anaconda3\envs\chanlunpy38\lib\site-packages\pandas\core\tools\datetimes.py", line 438, in _convert_listlike_datetimes
    result, tz_parsed = objects_to_datetime64ns(
  File "D:\anaconda3\envs\chanlunpy38\lib\site-packages\pandas\core\arrays\datetimes.py", line 2177, in objects_to_datetime64ns
    result, tz_parsed = tslib.array_to_datetime(
  File "pandas\_libs\tslib.pyx", line 427, in pandas._libs.tslib.array_to_datetime
  File "pandas\_libs\tslib.pyx", line 683, in pandas._libs.tslib.array_to_datetime
  File "pandas\_libs\tslib.pyx", line 829, in pandas._libs.tslib._array_to_datetime_object
  File "pandas\_libs\tslib.pyx", line 819, in pandas._libs.tslib._array_to_datetime_object
  File "pandas\_libs\tslibs\parsing.pyx", line 320, in pandas._libs.tslibs.parsing.parse_datetime_string
  File "D:\anaconda3\envs\chanlunpy38\lib\site-packages\dateutil\parser\_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "D:\anaconda3\envs\chanlunpy38\lib\site-packages\dateutil\parser\_parser.py", line 651, in parse
    six.raise_from(ParserError(str(e) + ": %s", timestr), e)
  File "<string>", line 3, in raise_from
dateutil.parser._parser.ParserError: month must be in 1..12: 0-00-00 15:00 present at position 102

**Comment by bopo** [comment]
问问题要会问
运行的什么代码，报的什么错，写清楚
