### ISSUE TITLE
关于client.quotes 请求000003代码时出现报错

### ISSUE THREAD

**Issue by bthuntergg** [mootdx/mootdx#42]
Traceback (most recent call last):
  File "D:/pythonProject/vnpy/vnpy_ths/mytest.py", line 134, in <module>
    data = client.quotes(symbol=['000003'])
  File "D:\ProgramData\anconda\envs\py38\lib\site-packages\mootdx\quotes.py", line 177, in quotes
    result = self.client.get_security_quotes(symbol)
  File "D:\ProgramData\anconda\envs\py38\lib\site-packages\tdxpy\base_socket_client.py", line 42, in wrapper
    raise ValidationException(*e.args)
tdxpy.exceptions.ValidationException: invalid literal for int() with base 10: ''

**Comment by bopo** [comment]
如果获取指数数据，要用 index 接口，不要用 quotes

**Comment by algoqt** [comment]
client = Quotes.factory(market='std')
symbol_sh = client.stocks(market=consts.MARKET_SH)

stock_sh = symbol_sh[[code[0]=="6" or code[0:1]=="90" for code in symbol_sh["code"]]]
etf_sh = symbol_sh[[code[0:2]=="51" or code[0:2]=="58" or code[0:2]=="56" for code in symbol_sh["code"]]]
for i in range(0,len(stock_sh['code']),80):
    _batch = list(stock_sh['code'])[i:i+80]
    print(i,_batch)
    x=client.quotes(symbol=_batch)

一次只能取80个股票代码？ 多了好像只返回80个。

# 轮询时 遇到  还没上市，比如 603296  会报错，不要抛出异常
for s in ['603296']:
    print(s)
    x=client.quotes(symbol=s)

Traceback (most recent call last):
  File "C:\Users\hongx\anaconda3\lib\site-packages\tdxpy\base_socket_client.py", line 39, in wrapper
    ret = func(self, *args, **kw)
  File "C:\Users\hongx\anaconda3\lib\site-packages\tdxpy\hq.py", line 108, in get_security_quotes
  File "C:\Users\hongx\anaconda3\lib\site-packages\tdxpy\parser\base.py", line 117, in call_api
    result = self._call_api()
  File "C:\Users\hongx\anaconda3\lib\site-packages\tdxpy\parser\base.py", line 194, in _call_api
    return self.parseResponse(body_buf)
  File "C:\Users\hongx\anaconda3\lib\site-packages\tdxpy\parser\std\get_security_quotes.py", line 136, in parseResponse
    ("servertime", self._format_time("%s" % reversed_bytes0)),
  File "C:\Users\hongx\anaconda3\lib\site-packages\tdxpy\parser\std\get_security_quotes.py", line 203, in _format_time
    if int(time_stamp[-6:-4]) < 60:
ValueError: invalid literal for int() with base 10: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "C:\Users\hongx\anaconda3\lib\site-packages\mootdx\quotes.py", line 177, in quotes
    result = self.client.get_security_quotes(symbol)
  File "C:\Users\hongx\anaconda3\lib\site-packages\tdxpy\base_socket_client.py", line 41, in wrapper
    raise ValidationException(*e.args)
tdxpy.exceptions.ValidationException: invalid literal for int() with base 10: ''

**Comment by bopo** [comment]
感谢你的建议，考虑新版调整
