### ISSUE TITLE
Affair.parse length mismatch

### ISSUE THREAD

**Issue by lynic** [mootdx/mootdx#45]
根据示例代码遇到了如下错误：
```
(base) root@f7584e55bf60:/opt/mootdx# pip list |grep mootdx
mootdx                  0.10.10

(base) root@f7584e55bf60:/opt/mootdx# python parse.py 
Traceback (most recent call last):
  File "/opt/mootdx/parse.py", line 3, in <module>
    data = Affair.parse(downdir="gpcw", filename="gpcw20221231.zip")
  File "/opt/conda/lib/python3.10/site-packages/mootdx/affair.py", line 68, in parse
    return financial.FinancialReader().to_data(filepath, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/mootdx/financial/financial.py", line 34, in to_data
    return crawler.to_df(data, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/mootdx/financial/financial.py", line 222, in to_df
    df.columns = columns
  File "/opt/conda/lib/python3.10/site-packages/pandas/core/generic.py", line 5915, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/opt/conda/lib/python3.10/site-packages/pandas/core/generic.py", line 823, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/opt/conda/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 230, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/opt/conda/lib/python3.10/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 582 elements, new values have 581 elements
```

**Comment by orzass** [comment]
看通达信软件FINVALUE公式的描述，应该是新增了 581 - 使用权资产折旧(万元)，直接在columns追加一行到信用减值后面就可以了。

**Comment by jonchin** [comment]
> 加在哪个文件？

**Comment by bopo** [comment]
新版本已经解决
