### ISSUE TITLE
读取商品期货数据5分钟和1分钟数据时解析的数据是错乱的

### ISSUE THREAD

**Issue by msia121** [mootdx/mootdx#65]
![image](https://github.com/mootdx/mootdx/assets/23181587/38b44570-4774-46b6-9b76-c9afab3a8d79)
无法正常解析日期

**Comment by lld1995** [comment]
。。我也发现这个问题了

**Comment by lld1995** [comment]
![image](https://github.com/mootdx/mootdx/assets/17978390/8c6a97e0-11cc-412c-963a-25fac27efb9f)
![image](https://github.com/mootdx/mootdx/assets/17978390/33fe0a61-4e2c-4a28-a095-90fd37b84d69)

这个地方没换reader，修改下即可

**Comment by bopo** [comment]
请详细说明

**Comment by lucifer-gx** [comment]
我也遇到了这个问题。
代码为：
from mootdx.reader import Reader

reader = Reader.factory(market='ext', tdxdir='c:/new_tdx')
r = reader.minute(symbol='30#RBL8')

print(r)

报错信息为：
site-packages\tdxpy\reader\exhq_daily_bar_reader.py:41: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df.index = pd.to_datetime(df.date)
Traceback (most recent call last):
  File "parsing.pyx", line 684, in pandas._libs.tslibs.parsing.dateutil_parse
ValueError: month must be in 1..12

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\MyCodes\MyQuantProject1\MyQuantProject1\test.py", line 4, in <module>
    r = reader.minute(symbol='30#RBL8')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MyCodes\MyQuantProject1\Lib\site-packages\mootdx\reader.py", line 193, in minute
    return self.reader.get_df(str(vipdoc)) if vipdoc else None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MyCodes\MyQuantProject1\Lib\site-packages\tdxpy\reader\exhq_daily_bar_reader.py", line 41, in get_df
    df.index = pd.to_datetime(df.date)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MyCodes\MyQuantProject1\Lib\site-packages\pandas\core\tools\datetimes.py", line 1067, in to_datetime
    values = convert_listlike(arg._values, format)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MyCodes\MyQuantProject1\Lib\site-packages\pandas\core\tools\datetimes.py", line 435, in _convert_listlike_datetimes
    result, tz_parsed = objects_to_datetime64(
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MyCodes\MyQuantProject1\Lib\site-packages\pandas\core\arrays\datetimes.py", line 2398, in objects_to_datetime64
    result, tz_parsed = tslib.array_to_datetime(
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "tslib.pyx", line 414, in pandas._libs.tslib.array_to_datetime
  File "tslib.pyx", line 596, in pandas._libs.tslib.array_to_datetime
  File "tslib.pyx", line 553, in pandas._libs.tslib.array_to_datetime
  File "conversion.pyx", line 641, in pandas._libs.tslibs.conversion.convert_str_to_tsobject
  File "parsing.pyx", line 336, in pandas._libs.tslibs.parsing.parse_datetime_string
  File "parsing.pyx", line 688, in pandas._libs.tslibs.parsing.dateutil_parse
pandas._libs.tslibs.parsing.DateParseError: month must be in 1..12: 3549-60-38, at position 0

进程已结束，退出代码为 1

看起来是tdxpy解析商品期货分钟线数据的时候哪里不对，解析出来的日期是错的。

**Comment by StarainX** [comment]
期货分钟时间算法和股票那边不一样所以报错了，函数定义里注释掉日期转换可以用，不过哪个日期格式比较奇怪是5869-21-85这种我还没搞明白。

**Comment by StarainX** [comment]
csdn上有解决思路的代码，可以参考一下。文章评论里有转换的工具
https://blog.csdn.net/bq_cui/article/details/128516899
