### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by itmorn** [mootdx/mootdx#80]
from mootdx.quotes import Quotes

client = Quotes.factory(market='std')

b = client.k(symbol='600056', begin="2000-10-26",end="2000-10-31",  adjust='qfq')
b.to_csv("b.csv")
print(b)

$ C:/ProgramData/miniconda3/python.exe c:/work/itmorn/AA_admin/tst.py
Traceback (most recent call last):
  File "c:\work\itmorn\AA_admin\tst.py", line 9, in <module>
    b = client.k(symbol='600056', begin="2000-10-26",end="2000-10-31",  adjust='qfq')
  File "C:\ProgramData\miniconda3\lib\site-packages\mootdx\quotes.py", line 423, in k
    return to_data(result, symbol=symbol, **kwargs)
  File "C:\ProgramData\miniconda3\lib\site-packages\mootdx\utils\__init__.py", line 170, in to_data
    result = to_adjust(result, symbol=symbol, adjust=adjust)
  File "C:\ProgramData\miniconda3\lib\site-packages\mootdx\utils\adjust.py", line 78, in to_adjust
    return reversion(symbol, temp_df, get_xdxr(symbol), adjust)
  File "C:\ProgramData\miniconda3\lib\site-packages\mootdx\tools\reversion.py", line 181, in reversion
    return factor_reversion(symbol=symbol, raw=stock_data, method=type_)
  File "C:\ProgramData\miniconda3\lib\site-packages\mootdx\tools\reversion.py", line 17, in factor_reversion
    data = pd.concat([raw, factor.loc[raw.index[0]: raw.index[-1], ['factor']]], axis=1)
  File "C:\ProgramData\miniconda3\lib\site-packages\pandas\core\indexes\base.py", line 5366, in __getitem__
    return getitem(key)
  File "C:\ProgramData\miniconda3\lib\site-packages\pandas\core\arrays\datetimelike.py", line 376, in __getitem__
    result = cast("Union[Self, DTScalarOrNaT]", super().__getitem__(key))
  File "C:\ProgramData\miniconda3\lib\site-packages\pandas\core\arrays\_mixins.py", line 276, in __getitem__
    result = self._ndarray[key]
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by bopo** [comment]
好的，我实验下
